"""Modified all borrowings table

Revision ID: 8732353f272d
Revises: 
Create Date: 2024-08-11 01:54:31.310491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8732353f272d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_borrowings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_borrowings', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
